package;


import com.gs.KonsoleDemo;
import com.gs.console.Konsole;
import com.gs.console.KonsoleConfig;
import com.gs.console.KonsoleView;
import com.gs.femto_ui.Align;
import com.gs.femto_ui.Button;
import com.gs.femto_ui.Label;
import com.gs.femto_ui.Root;
import com.gs.femto_ui.Viewport;
import flash.display.Sprite;
import flash.events.Event;
import flash.events.MouseEvent;
import flash.text.TextField;
import haxe.Timer;
import haxe.unit.TestRunner;

//TODO review: \Pictures\bug_bug.png
/*
DumpDefines.hx:19: {fdb => 1, js => 1, AIR_SDK => e:\Flash\SDK_Air290, hscript => 2.2.0, source-header => Generated by Haxe 3.4.7, lime-howlerjs => 1,
jquery_ver => 11204, lime_howlerjs => 1, openfl => 8.4.1, lime_dom => 1, lime_html5 => 1, no-compilation => 1, lime_webgl => 1, openfl_html5 => 1,
lime-html5 => 1, openfl-html5 => 1, howlerjs => 1, haxe_ver => 3.407, debug => 1, js_es => 5, js-es5 => 1, js_es5 => 1, dce => std, lime-dom => 1,
true => 1, html5 => 1, lime => 7.0.0, no_compilation => 1, web => 1, lime_canvas => 1, lime-webgl => 1, tools => 7.0.0, haxe3 => 1, lime-canvas => 1}
*/

class Main extends Sprite
{
	var counter_: Int = 0;
	var tf_: TextField = null;
	var b2: Button = null;
	var al_: Label = null;
	var vp: Viewport = null;
	var k: Konsole = null;

	public function new()
	{

		super ();

		DumpDefines.dump();
		//trace("Hello, OpenFL");
		test1();
		//test2();
		//test3();
	}

	function test1()
	{
		var tr = new TestRunner();
		tr.add(new TestRingBuf());
		tr.add(new TestNumUtils());
		tr.add(new TestStrUtils());
		tr.run();

	}

	/*
	function test2()
	{
		var r: Root = Root.create(stage);

		al_ = new Label(stage, "Hello, Мир!");
		al_.movesize(10, 20, 220, 140);
		al_.dummy_color = 0xc00000;
		al_.h_align = Align.CENTER;

		var b: Button = new Button(stage, "foo", on_Click);
		b.dummy_color = 0x0000c0;
		b.movesize(250, 20, 220, 40);

		b2 = new Button(stage, "align", on_Click2);
		b2.dummy_color = 0x0000c0;
		b2.movesize(250, 120, 220, 40);

		vp = new Viewport(stage);
		vp.dummy_color = 0x80dFdF51;
		vp.movesize(100, 250, 120, 120);
	}

	function on_Click2(e: MouseEvent)
	{
		switch(al_.h_align)
		{
			case Align.NEAR:
				al_.h_align = Align.CENTER;
			case Align.CENTER:
				al_.h_align = Align.FAR;
			case Align.FAR:
				al_.h_align = Align.NEAR;
		}
	}

	function on_Click(e: Event)
	{
		trace("click!");
		al_.text += "\nclick #" + counter_++;
		b2.enabled = !b2.enabled;
		if (!vp.visible)
			vp.visible = true;
	}
	*/

	function test3()
	{
		tf_ = new TextField();
		addChild(tf_);
		tf_.x = 10;
		tf_.y = 20;
		tf_.htmlText = "1<br>";
		tf_.htmlText += "2<br>";
		tf_.htmlText = "<p>1</p>";
		tf_.htmlText += "<p>2</p>";
		tf_.htmlText += "<p>1</p><p>2</p>";

		KonsoleDemo.create_UI(this);
	}



}