package;


import KonsoleDemo;
import gs.femto_ui.util.DumpDefines;
import flash.display.Sprite;

//TODO review: \Pictures\bug_bug.png
/*
DumpDefines.hx:19: {fdb => 1, js => 1, AIR_SDK => e:\Flash\SDK_Air290, hscript => 2.2.0, source-header => Generated by Haxe 3.4.7, lime-howlerjs => 1,
jquery_ver => 11204, lime_howlerjs => 1, openfl => 8.4.1, lime_dom => 1, lime_html5 => 1, no-compilation => 1, lime_webgl => 1, openfl_html5 => 1,
lime-html5 => 1, openfl-html5 => 1, howlerjs => 1, haxe_ver => 3.407, debug => 1, js_es => 5, js-es5 => 1, js_es5 => 1, dce => std, lime-dom => 1,
true => 1, html5 => 1, lime => 7.0.0, no_compilation => 1, web => 1, lime_canvas => 1, lime-webgl => 1, tools => 7.0.0, haxe3 => 1, lime-canvas => 1}
*/

class Main extends Sprite
{
	//var tf_: TextField = null;

	public function new()
	{

		super ();

		//trace("Hello, OpenFL");
		//test1();
		test3();
		//DumpDefines.dump();
	}

	/*
	function test1()
	{
		var tr = new TestRunner();
		tr.add(new TestRingBuf());
		tr.add(new TestNumUtils());
		tr.add(new TestStrUtils());
		tr.run();
	}
	*/


	function test3()
	{
		/*
		tf_ = new TextField();
		addChild(tf_);
		tf_.x = 10;
		tf_.y = 20;
		tf_.htmlText = "1<br>";
		tf_.htmlText += "2<br>";
		tf_.htmlText = "<p>1</p>";
		tf_.htmlText += "<p>2</p>";
		tf_.htmlText += "<p>1</p><p>2</p>";
		*/
		KonsoleDemo.create_UI(this);
	}



}